### ISSUE TITLE
点击启用一片空白

### ISSUE THREAD

**Issue by levinit** [rainfroid/Typecho-Plugin-CommentToMail#1]
其他插件并没有问题。请问怎么回事？
再问一个，插件名是Typecho-Plugin-CommentTomail还是CommentTomail，解压后文件夹用哪个名字
？

**Comment by sylviax26** [comment]
已收到，插件名是CommentTomail，文件夹名同

已复现，正在检查了

**Comment by sylviax26** [comment]
已修复，感谢，如有问题欢迎再次提出。
