### ISSUE TITLE
有人评论（或回复）收不到邮件提醒

### ISSUE THREAD

**Issue by sxgxhk** [rainfroid/Typecho-Plugin-CommentToMail#2]
邮件设置也都弄了，测试发送的时候也成功的，但是有人评论（或回复）时却收不到邮件提醒，还请指教

**Comment by sylviax26** [comment]
周六处理

**Comment by sylviax26** [comment]
自己写着玩自用的插件，突然来了好多人，好方~

刚刚全新安装测试了一遍，发现了之前更改了数据表结构，没有同步到sql文件中。
可能造成插入数据过长被截断，检查typecho_mail表的content数据有没有提前终止。
如果是此问题的话，将此表的content和log的类型由varchar改为text即可
