### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by zhiyuan1i** [rainfroid/Typecho-Plugin-CommentToMail#5]
能不能cron取消对于只能服务器自己访问的限定，我想通过阿里/360网址监控运行
而且你的版本QQ邮箱发信有问题，我做了一定修改！
详情见 https://blog.zhiyuanyun.cc/lab.html

**Comment by sylviax26** [comment]
感谢建议，后续我将全部重写此插件，此repo暂不维护。

**Comment by zhiyuan1i** [comment]
嗯嗯！貌似也可以直接网址监控，不过你的PHPmailer太老了……有的有些问题呢

**Comment by sylviax26** [comment]
之前尝试过更新这个库，然后出现了一些问题并且不能稳定复现，不好确定是什么引起的，我就退回旧版了

**Comment by zhiyuan1i** [comment]
我尝试修改后没啥问题，也借鉴了别人的做法！
