### ISSUE TITLE
请问设置Cron定时发送那里应该怎么写？

### ISSUE THREAD

**Issue by AlanDecode** [rainfroid/Typecho-Plugin-CommentToMail#6]
任务写成 /usr/bin/curl https://…这样可以吗？
我尝试直接curl这个网址，返回的内容里写 no permission。在本地用浏览器访问是没问题。

我不太了解这方面的东西，麻烦了

**Comment by sylviax26** [comment]
URL是怎么写的，链接里的key值正确吗

**Comment by AlanDecode** [comment]
URL类似这样：https://blog.imalan.me/action/comment-to-mail?do=deliverMail&key=980KP5uD2xxxxx。
这个URL用Chrome访问是没问题的，curl就no permission，在插件里打开开启不验证key的选项用
https://blog.imalan.me/commentToMailProcessQueue/来执行是没问题的。

**Comment by sylviax26** [comment]
检查一下你的cron设置？
浏览器可以的话，curl应该也没问题。

**Comment by AlanDecode** [comment]
我用Windows上的curl访问也不行，对curl有什么要求吗？

**Comment by sylviax26** [comment]
测试curl没有问题，贴一下你的cron配置吧

**Comment by AlanDecode** [comment]
你是说cron任务？

*/5 * * * * /usr/bin/curl https://blog.imalan.me/commentToMailProcessQueue/  这样可以
*/5 * * * * /usr/bin/curl https://blog.imalan.me/action/comment-to-mail?do=deliverMail&key=980KP5uD2ejRxxxx  这样就不行

**Comment by sylviax26** [comment]
URL用引号括起来试试，&是shell的特殊字符

**Comment by AlanDecode** [comment]
对就是这个问题，谢谢了
